"use client";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarLayout, SidebarTrigger } from "@/components/ui/sidebar";
import React from "react";

import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sidebarOpen = true;

  const noSidebar = ["/login", "/forgot-password", "/signup"];

  const path = usePathname();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        {/* / check route is login or forgot password or sign  */}
        {
          // if route is login or forgot password or sign up
          // then render the children
          // else render the sidebar layout
        }

        {noSidebar.includes(path) ? (
          children
        ) : (
          <SidebarLayout
            defaultOpen={
              // if route is login or forgot password or sign up
              // then render the children
              // else render the sidebar layout
              sidebarOpen
            }
          >
            <AppSidebar />
            <main className="flex flex-1 flex-col p-2 transition-all duration-300 ease-in-out">
              <div className="h-full">
                <SidebarTrigger />
                {children}
              </div>
            </main>
          </SidebarLayout>
        )}
      </body>
    </html>
  );
}
